= LVM format specification
Analysis of the Logical Volume Manager format

:numbered!:
[abstract]
== Summary
The Logical Volume Manager (LVM) is a volume manager for Linux, although the 
term is used for other Unix implementations as well.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about Logical Volume Manager (LVM) format.
| Classification: | Public
| Keywords: | Logical Volume Manager, LVM
|===

[preface]
== License
....
Copyright (C) 2013-2014, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the 
terms of the GNU Free Documentation License, Version 1.3 or any later version 
published by the Free Software Foundation; with no Invariant Sections, no 
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included 
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | July 2013 | Initial version.
| 0.0.2 | J.B. Metz | February 2014 | Additional information.
| 0.0.3 | J.B. Metz | July 2014 | Additional information.
| 0.0.4 | J.B. Metz | November 2014 | Switched to asccidoc format.
|===

:numbered:
== Overview
The Logical Volume Manager (LVM) is a volume manager for Linux, although the 
term is used for other Unix implementations as well.

=== Terminology

[cols="1,3",options="header"]
|===
| Term | Description
| logical extent (LE) | An extent (data range) that makes up the logical volume.
| logical volume (LV) | A volume within the LVM, equivalent to a disk partition in e.g. the MBR or GPT volume system.
| physical extent (PE) | An extent (data range) that makes up the physical volume.
| physical volume (PV) | Typically a physical volume is a hard disk, though it may well just be a device that 'looks' like a hard disk (e.g. a software RAID device).
| volume group (VG) | A collection of Logical Volumes and Physical Volumes.
|===

=== Layout
An LVM volume consist of:

* Volume group
* Physical volumes
* Logical volumes

An Physical volume consist of:

* Empty sector
* The physical volume label header
** The physical volume header
*** data area descriptor list
*** metadata area descriptor list
* The metadata area
* Data area (or data extents)

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values |
| Character strings | ASCII string with an end-of-string character
|===

=== Test version
The following version of programs were used to test the information within this 
document:

* lvm2

== Physical volume label
The physical volume label is stored in the second sector of the physical 
volume. The physical volume label consists of:

* physical volume label header
* physical volume header

[NOTE]
According to [REDHAT] the physical volume label can be stored in any of the 
first four sectors.

=== Physical volume label header
The physical volume label header (struct label_header) is 32 bytes in size and 
consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | "LABELONE" | Signature (or identifier)
| 8 | 8 | | Sector number +
The sector number of the physical volume label header
| 16 | 4 | | Checksum +
CRC-32 for offset 20 to end of the physical volume label sector
| 20 | 4 | | Data offset (or header size) +
The offset, in bytes, relative from the start of the physical volume label header
| 24 | 8 | "LVM2\x20001" | Type indicator
|===

=== Physical volume header
The physical volume header (struct pv_header) is variable in size and consist 
of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 32 | | Physical volume identifier +
Contains a UUID stored as an ASCII string.
| 32 | 8 | | Physical volume size +
Value in bytes
| 40 | ... | | List of data area descriptors +
The last descriptor in the list is terminator and consists of 0-byte values. +
See section: <<data_area_descriptor,Data area descriptor>>
| ... | ... | | List of metadata area descriptors +
The last descriptor in the list is terminator and consists of 0-byte values. +
See section: <<data_area_descriptor,Data area descriptor>>
|===

The physical volume identifier can be used to uniquely identify a physical 
volume. The physical volume identifier is stored as: 
9LBcEB7PQTGIlLI0KxrtzrynjuSL983W but is equivalent to its formatted variant: 
9LBcEB-7PQT-GIlL-I0Kx-rtzr-ynju-SL983W, which is used in the metadata.

[NOTE]
The data area size can be 0. [yellow-background]*Does this represent all remaining available space?*

==== [[data_area_descriptor]]Data area descriptor

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Data area offset +
The offset, in bytes, relative from the start of the physical volume
| 8 | 8 | | Data area size +
Value in bytes
|===

== The metadata area
The metadata area consist of:

* Metadata area header
* Metadata

According to `[REDHAT]` the metadata area is a circular buffer. New metadata is 
appended to the old metadata and then the pointer to the start of it is 
updated. The metadata area, therefore, can contain copies of older versions of 
the metadata.

=== Metadata area header
The metadata area header (struct mda_header) is variable in size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Checksum +
CRC-32 for offset 4 to end of the metadata area header
| 4 | 16 | "\x20LVM2\x20x[5A%r0N*>" | Signature
| 20 | 4 | 1 | Version
| 24 | 8 | | Metadata area offset +
Value in bytes +
The offset, in bytes, of the metadata area relative from the start of the physical volume
| 32 | 8 | | Metadata area size +
The size of the metadata area in bytes
| 40 | ...  | | List of raw location descriptors +
The last descriptor in the list is terminator and consists of 0-byte values. +
See section: <<raw_location_descriptor,Raw location descriptor>>
|===

==== [[raw_location_descriptor]]Raw location descriptor
The raw location descriptor (struct raw_locn) is 24 bytes in size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Data area offset +
The offset, in bytes, relative from the start of the metadata area
| 8 | 8 | | Data area size +
Value in bytes
| 16 | 4 | | Checksum +
CRC-32 of [yellow-background]*TODO (metadata?)*
| 20 | 4 | | Flags +
See section: <<raw_location_descriptor_flags,Raw location descriptor flags>>
|===

==== [[raw_location_descriptor_flags]]Raw location descriptor flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | RAW_LOCN_IGNORED | The raw location descriptor should be ignored.
|===

== Metadata
The metadata consist of:

* Volume group main section
** Physical volumes sub section
*** Physical volume sub sections
** Logical volumes sub section
*** Logical volume sub sections
**** Segment sub section
* Global parameters

According to `[REDHAT]` by default, an identical copy of the metadata is 
maintained in every metadata area in every physical volume within the volume 
group. The metadata is stored as ASCII.

The metadata can also be stored in a stand-alone file.

=== Parameter definitions
The metadata sections are textual and use the following parameter definitions.

A parameter is defined as:
....
<identifier> = <value>
....

Where <identifier> contains a unique name of the parameter and <value> is one 
of the following types:

[cols="1,3",options="header"]
|===
| Value | Description
| [0-9]+ | An integer
| "..." | A string
| ["...", "...", ...] | A list (or array) of strings
|===

[NOTE]
White space like space and new line characters seem to be ignored.

The # character is used for comments. A comment continues to the end-of-line.

[NOTE]
For now it is assumed that the # character is not allowed to be used in any of the values.

=== Volume group main section
The volume group main section is defined as:
....
<name> {
<parameters>
<sub sections>
}
....

Where:

* <name> contains the name of the volume group.
* <parameters> contains one of the following parameters:

[yellow-background]*Note can there be more than 1 volume group?*

[cols="1,3",options="header"]
|===
| Value | Description
| id | Volume group identifier (VG UUID) +
Contains an ASCII string in the following format: fg1fKZ-xoHz-CfAD-yQPx-l2HL-Y7kA-9kJ9LD
| seqno | Metadata sequence number
| status | The status flags +
Contains a list of strings. See section: <<status_flags,Status flags>>
| flags | The flags +
Contains a list of strings. See section: <<flags,Flags>>
| extent_size | The size of an extent +
The value contains the number of sectors +
[yellow-background]*Note that the sector size is currently assumed to be 512 bytes.*
| max_lv | Maximum number of logical volumes
| max_pv | Maximum number of physical volumes
| metadata_copies | [yellow-background]*The number of metadata copies?*
|===

<sub sections> contains one of the following sub sections:

[cols="1,3",options="header"]
|===
| Value | Description
| physical_volumes | The physical volumes sub sections
| logical_volumes | The logical volumes sub sections
|===

=== Physical volumes sub section
The physical volumes sub section is defined as:
....
physical_volumes { 
<sub sections>
}
....

Where:

* <sub sections> contains one of the following sub sections:

[cols="1,3",options="header"]
|===
| Value | Description
| pv# | Individual physical volume sub section +
Where # is a place holder for a the physical volume number e.g. pv0. 0 appears to be the first number that is used.
|===

=== Physical volume sub section
Each physical volume sub section is defined as:
....
pv# {
<parameters>
}
....

Where:

* # is a place holder for a the physical volume number e.g. pv0
* <parameters> contains one of the following parameters:

[cols="1,3",options="header"]
|===
| Value | Description
| id | Physical volume identifier (PV UUID) +
Contains an ASCII string in the following format: 9LBcEB-7PQT-GIlL-I0Kx-rtzr-ynju-SL983W
| device | The device filename +
Contains an ASCII string e.g. /dev/dm-0
| status | The status flags +
Contains a list of strings. See section: <<status_flags,Status flags>>
| dev_size | The physical volume size including non-usable space +
The value contains the number of sectors +
[yellow-background]*Note that the sector size is currently assumed to be 512 bytes.*
| pe_start | The start extent
| pe_count | The number of (allocated) extents in the physical volume
|===

=== Logical volumes sub section
The logical volumes sub section is defined as:
....
logical_volumes { 
<sub sections>
}
....

Where:

* <sub sections> contains one of the following sub sections:

[cols="1,3",options="header"]
|===
| Value | Description
| <name> | Individual physical volume sub section +
Where <name> is a place holder for a the logical volume name
|===

=== Logical volume sub section
Each logical volume sub section is defined as:
....
<name> {
<parameters>
<sub sections>
}
....

Where:

* <name> contains the name of the physical volume

Some implementations use lv_ as the prefix for a logical volume note that the 
format does not imply this convention.

* <parameters> contains one of the following parameters:

[cols="1,3",options="header"]
|===
| Value | Description
| id | Physical volume identifier (PV UUID) +
Contains an ASCII string in the following format: 9LBcEB-7PQT-GIlL-I0Kx-rtzr-ynju-SL983W
| status | The status flags +
Contains a list of strings. See section: <<status_flags,Status flags>>
| flags | The flags +
Contains a list of strings. See section: <<flags,Flags>>
| segment_count | The number of segment sub sections
|===

* <sub sections> contains one of the following sub sections:

[cols="1,3",options="header"]
|===
| Value | Description
| segment# | Individual physical volume sub section +
Where # is a place holder for the segment number e.g. segment1. 1 appears to be the first number that is used.
|===

=== Segment sub section
Each segment sub section is defined as:
....
segment# {
<parameters>
}
....

Where:

* # is a place holder for the segment number e.g. segment1
* <parameters> contains one of the following parameters:

[cols="1,3",options="header"]
|===
| Value | Description
| start_extent | The start extent of the segment +
The number is relative to the start of the segment
| extent_count | The number of extents in the segment (or current logical extent)
| type | The segment type +
See section: <<segment_types,Segment types>>
| stripe_count | The number of stripes in the segment +
[yellow-background]*1 => linear* +
[yellow-background]*multiple stripes for different "RAID" variants?*
| stripes | The stripes list
|===

=== [[segment_types]]Segment types

[cols="1,3",options="header"]
|===
| Value | Description
| striped | Is striped
|===

=== Stripes list
....
stripes = [
<physical volume name>, <start extent number>
]
....

Where:

* <physical volume name> is a string containing the physical volume name e.g. "pv0".
* <start extent number> the segment start extent number relative from the start of the data area.

=== Global parameters

[cols="1,3",options="header"]
|===
| Value | Description
| contents | The contents of the metadata area +
A string containing "Text Format Volume Group"
| version | The metadata area version +
A numeric value containing 1
| description | [yellow-background]*Description of the metadata area?*
| creation_host | The hostname of the system on which metadata area was created +
Can have a trailing comment that contains the output equivalent to "uname -a".
| creation_time | The creation time of the metadata area +
Contains a numeric value of the number of seconds since January 1, 1970 00:00:00 UTC. +
Can have a trailing comment that contains the creation time as a ctime (function) string in UTC.
|===

=== [[status_flags]]Status flags

[cols="1,3",options="header"]
|===
| Value | Description
| ALLOCATABLE | Is allocatable [physical volume only]
| RESIZEABLE | Can be re-sized [volume group only]
| READ | Can be read
| VISIBLE | Is visible [logical volume only]
| WRITE | Can be written
|===

=== [[flags]]Flags

[cols="1,3",options="header"]
|===
| Value | Description
| | [yellow-background]*TODO*
|===

=== Comments
Some of the comment in the metadata can be interesting for forensic analysis 
e.g. the version of LVM used.

....
# Generated by LVM2 version 2.02.39 (2008-06-27): Sat Jan 17 11:45:29 2009 
....

== Notes
=== Reading data
Get the lv start extent
lv offset = extent x extent size
physical volume offset = data area offset + lv offset

=== Tools

* vgdisplay
* pvdisplay
* lvdisplay

=== Mapping modes
http://www.tldp.org/HOWTO/LVM-HOWTO/mapmode.html

=== Snapshots
http://www.tldp.org/HOWTO/LVM-HOWTO/snapshotintro.html

=== Metadata
1 sector: metadata area header – pointer to metadata 
circular buffer, text format (at least 2 versions of metadata) 
atomic update – 1) write new version 2) update pointer 
SEQNO – sequential number 
checksum, redundancy, autorepair

=== Metadata sample
....
# Generated by LVM2: Tue Jan 30 16:28:15 2007

contents = "Text Format Volume Group"
version = 1

description = "Created *before* executing 'lvextend -L+5G /dev/myvg/mylv /dev/sdc'"

creation_host = "tng3-1"  # Linux tng3-1 2.6.18-8.el5 #1 SMP Fri Jan 26 14:15:21 EST 2007 i686
creation_time = 1170196095  # Tue Jan 30 16:28:15 2007

myvg {
  id = "0zd3UT-wbYT-lDHq-lMPs-EjoE-0o18-wL28X4"
  seqno = 3
  status = ["RESIZEABLE", "READ", "WRITE"]
  extent_size = 8192    # 4 Megabytes
  max_lv = 0
  max_pv = 0

  physical_volumes {

    pv0 {
      id = "ZBW5qW-dXF2-0bGw-ZCad-2RlV-phwu-1c1RFt"
      device = "/dev/sda"   # Hint only

      status = ["ALLOCATABLE"]
      dev_size = 35964301   # 17.1491 Gigabytes
      pe_start = 384
      pe_count = 4390 # 17.1484 Gigabytes
    }

    pv1 {
      id = "ZHEZJW-MR64-D3QM-Rv7V-Hxsa-zU24-wztY19"
      device = "/dev/sdb"   # Hint only

      status = ["ALLOCATABLE"]
      dev_size = 35964301   # 17.1491 Gigabytes
      pe_start = 384
      pe_count = 4390 # 17.1484 Gigabytes
    }

    pv2 {
      id = "wCoG4p-55Ui-9tbp-VTEA-jO6s-RAVx-UREW0G"
      device = "/dev/sdc"   # Hint only

      status = ["ALLOCATABLE"]
      dev_size = 35964301   # 17.1491 Gigabytes
      pe_start = 384
      pe_count = 4390 # 17.1484 Gigabytes
    }

    pv3 {
      id = "hGlUwi-zsBg-39FF-do88-pHxY-8XA2-9WKIiA"
      device = "/dev/sdd"   # Hint only

      status = ["ALLOCATABLE"]
      dev_size = 35964301   # 17.1491 Gigabytes
      pe_start = 384
      pe_count = 4390 # 17.1484 Gigabytes
    }
  }
  logical_volumes {

    mylv {
      id = "GhUYSF-qVM3-rzQo-a6D2-o0aV-LQet-Ur9OF9"
      status = ["READ", "WRITE", "VISIBLE"]
      segment_count = 2

      segment1 {
        start_extent = 0
        extent_count = 1280   # 5 Gigabytes

        type = "striped"
        stripe_count = 1  # linear

        stripes = [
          "pv0", 0
        ]
      }
      segment2 {
        start_extent = 1280
        extent_count = 1280   # 5 Gigabytes

        type = "striped"
        stripe_count = 1  # linear

        stripes = [
          "pv1", 0
        ]
      }
    }
  }
}
....

=== Building a test file
....
dd if=/dev/zero of=image.raw bs=512 count=$(( 256 * 1024 * 2 ))

sudo losetup /dev/loop1 image.raw

sudo pvcreate /dev/loop1

sudo vgcreate vg_test /dev/loop1

sudo lvcreate -L 75M --name lv_test1 vg_test

sudo losetup -d /dev/loop1
....

:numbered!:
[appendix]
== References

[cols="1,5",options="header"]
|===
| Title: | LVM-HOWTO
| URL: | http://www.tldp.org/HOWTO/LVM-HOWTO/mapmode.html
|===

[cols="1,5",options="header"]
|===
| Title: | LVM1 source code
| URL: | ftp://sources.redhat.com/pub/lvm/current/
|===

[cols="1,5",options="header"]
|===
| Title: | LVM2 source code
| URL: | ftp://sources.redhat.com/pub/lvm2/
|===

`[BROZ09]`

[cols="1,5",options="header"]
|===
| Title: | LVM2 – data recovery
| Author(s): | Milan Brož
| Date: | 2009
| URL: | http://lvb.sti.fce.vutbr.cz/public/LinuxAlt_2009/2009_11_08_LA_04_LVM/2009_11_08_LA_04_LVM.pdf
|===

`[REDHAT]`

[cols="1,5",options="header"]
|===
| Title: | Appendix D. LVM Volume Group Metadata
| Date: | January 31, 2013
| URL: | https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Logical_Volume_Manager_Administration/lvm_metadata.html
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc. 
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license 
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional 
and useful document "free" in the sense of freedom: to assure everyone the 
effective freedom to copy and redistribute it, with or without modifying it, 
either commercially or noncommercially. Secondarily, this License preserves for 
the author and publisher a way to get credit for their work, while not being 
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the 
document must themselves be free in the same sense. It complements the GNU 
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software, 
because free software needs free documentation: a free program should come with 
manuals providing the same freedoms that the software does. But this License is 
not limited to software manuals; it can be used for any textual work, 
regardless of subject matter or whether it is published as a printed book. We 
recommend this License principally for works whose purpose is instruction or 
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains 
a notice placed by the copyright holder saying it can be distributed under the 
terms of this License. Such a notice grants a world-wide, royalty-free license, 
unlimited in duration, to use that work under the conditions stated herein. The 
"Document", below, refers to any such manual or work. Any member of the public 
is a licensee, and is addressed as "you". You accept the license if you copy, 
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or 
a portion of it, either copied verbatim, or with modifications and/or 
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the 
Document that deals exclusively with the relationship of the publishers or 
authors of the Document to the Document's overall subject (or to related 
matters) and contains nothing that could fall directly within that overall 
subject. (Thus, if the Document is in part a textbook of mathematics, a 
Secondary Section may not explain any mathematics.) The relationship could be a 
matter of historical connection with the subject or with related matters, or of 
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are 
designated, as being those of Invariant Sections, in the notice that says that 
the Document is released under this License. If a section does not fit the 
above definition of Secondary then it is not allowed to be designated as 
Invariant. The Document may contain zero Invariant Sections. If the Document 
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as 
Front-Cover Texts or Back-Cover Texts, in the notice that says that the 
Document is released under this License. A Front-Cover Text may be at most 5 
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented 
in a format whose specification is available to the general public, that is 
suitable for revising the document straightforwardly with generic text editors 
or (for images composed of pixels) generic paint programs or (for drawings) 
some widely available drawing editor, and that is suitable for input to text 
formatters or for automatic translation to a variety of formats suitable for 
input to text formatters. A copy made in an otherwise Transparent file format 
whose markup, or absence of markup, has been arranged to thwart or discourage 
subsequent modification by readers is not Transparent. An image format is not 
Transparent if used for any substantial amount of text. A copy that is not 
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without 
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly 
available DTD, and standard-conforming simple HTML, PostScript or PDF designed 
for human modification. Examples of transparent image formats include PNG, XCF 
and JPG. Opaque formats include proprietary formats that can be read and edited 
only by proprietary word processors, SGML or XML for which the DTD and/or 
processing tools are not generally available, and the machine-generated HTML, 
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such 
following pages as are needed to hold, legibly, the material this License 
requires to appear in the title page. For works in formats which do not have 
any title page as such, "Title Page" means the text near the most prominent 
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the 
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title 
either is precisely XYZ or contains XYZ in parentheses following text that 
translates XYZ in another language. (Here XYZ stands for a specific section 
name mentioned below, such as "Acknowledgements", "Dedications", 
"Endorsements", or "History".) To "Preserve the Title" of such a section when 
you modify the Document means that it remains a section "Entitled XYZ" 
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states 
that this License applies to the Document. These Warranty Disclaimers are 
considered to be included by reference in this License, but only as regards 
disclaiming warranties: any other implication that these Warranty Disclaimers 
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or 
noncommercially, provided that this License, the copyright notices, and the 
license notice saying this License applies to the Document are reproduced in 
all copies, and that you add no other conditions whatsoever to those of this 
License. You may not use technical measures to obstruct or control the reading 
or further copying of the copies you make or distribute. However, you may 
accept compensation in exchange for copies. If you distribute a large enough 
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may 
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed 
covers) of the Document, numbering more than 100, and the Document's license 
notice requires Cover Texts, you must enclose the copies in covers that carry, 
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front 
cover, and Back-Cover Texts on the back cover. Both covers must also clearly 
and legibly identify you as the publisher of these copies. The front cover must 
present the full title with all words of the title equally prominent and 
visible. You may add other material on the covers in addition. Copying with 
changes limited to the covers, as long as they preserve the title of the 
Document and satisfy these conditions, can be treated as verbatim copying in 
other respects.

If the required texts for either cover are too voluminous to fit legibly, you 
should put the first ones listed (as many as fit reasonably) on the actual 
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than 
100, you must either include a machine-readable Transparent copy along with 
each Opaque copy, or state in or with each Opaque copy a computer-network 
location from which the general network-using public has access to download 
using public-standard network protocols a complete Transparent copy of the 
Document, free of added material. If you use the latter option, you must take 
reasonably prudent steps, when you begin distribution of Opaque copies in 
quantity, to ensure that this Transparent copy will remain thus accessible at 
the stated location until at least one year after the last time you distribute 
an Opaque copy (directly or through your agents or retailers) of that edition 
to the public.

It is requested, but not required, that you contact the authors of the Document 
well before redistributing any large number of copies, to give them a chance to 
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the 
conditions of sections 2 and 3 above, provided that you release the Modified 
Version under precisely this License, with the Modified Version filling the 
role of the Document, thus licensing distribution and modification of the 
Modified Version to whoever possesses a copy of it. In addition, you must do 
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that 
of the Document, and from those of previous versions (which should, if there 
were any, be listed in the History section of the Document). You may use the 
same title as a previous version if the original publisher of that version 
gives permission. 

B. List on the Title Page, as authors, one or more persons or entities 
responsible for authorship of the modifications in the Modified Version, 
together with at least five of the principal authors of the Document (all of 
its principal authors, if it has fewer than five), unless they release you from 
this requirement. 

C. State on the Title page the name of the publisher of the Modified Version, 
as the publisher. 

D. Preserve all the copyright notices of the Document. 

E. Add an appropriate copyright notice for your modifications adjacent to the 
other copyright notices. 

F. Include, immediately after the copyright notices, a license notice giving 
the public permission to use the Modified Version under the terms of this 
License, in the form shown in the Addendum below. 

G. Preserve in that license notice the full lists of Invariant Sections and 
required Cover Texts given in the Document's license notice. 

H. Include an unaltered copy of this License. 

I. Preserve the section Entitled "History", Preserve its Title, and add to it 
an item stating at least the title, year, new authors, and publisher of the 
Modified Version as given on the Title Page. If there is no section Entitled 
"History" in the Document, create one stating the title, year, authors, and 
publisher of the Document as given on its Title Page, then add an item 
describing the Modified Version as stated in the previous sentence. 

J. Preserve the network location, if any, given in the Document for public 
access to a Transparent copy of the Document, and likewise the network 
locations given in the Document for previous versions it was based on. These 
may be placed in the "History" section. You may omit a network location for a 
work that was published at least four years before the Document itself, or if 
the original publisher of the version it refers to gives permission. 

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the 
Title of the section, and preserve in the section all the substance and tone of 
each of the contributor acknowledgements and/or dedications given therein. 

L. Preserve all the Invariant Sections of the Document, unaltered in their text 
and in their titles. Section numbers or the equivalent are not considered part 
of the section titles. 

M. Delete any section Entitled "Endorsements". Such a section may not be 
included in the Modified Version. 

N. Do not retitle any existing section to be Entitled "Endorsements" or to 
conflict in title with any Invariant Section. 

O. Preserve any Warranty Disclaimers. 

If the Modified Version includes new front-matter sections or appendices that 
qualify as Secondary Sections and contain no material copied from the Document, 
you may at your option designate some or all of these sections as invariant. To 
do this, add their titles to the list of Invariant Sections in the Modified 
Version's license notice. These titles must be distinct from any other section 
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but 
endorsements of your Modified Version by various parties—for example, 
statements of peer review or that the text has been approved by an organization 
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage 
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts 
in the Modified Version. Only one passage of Front-Cover Text and one of 
Back-Cover Text may be added by (or through arrangements made by) any one 
entity. If the Document already includes a cover text for the same cover, 
previously added by you or by arrangement made by the same entity you are 
acting on behalf of, you may not add another; but you may replace the old one, 
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give 
permission to use their names for publicity for or to assert or imply 
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License, 
under the terms defined in section 4 above for modified versions, provided that 
you include in the combination all of the Invariant Sections of all of the 
original documents, unmodified, and list them all as Invariant Sections of your 
combined work in its license notice, and that you preserve all their Warranty 
Disclaimers.

The combined work need only contain one copy of this License, and multiple 
identical Invariant Sections may be replaced with a single copy. If there are 
multiple Invariant Sections with the same name but different contents, make the 
title of each such section unique by adding at the end of it, in parentheses, 
the name of the original author or publisher of that section if known, or else 
a unique number. Make the same adjustment to the section titles in the list of 
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the 
various original documents, forming one section Entitled "History"; likewise 
combine any sections Entitled "Acknowledgements", and any sections Entitled 
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents 
released under this License, and replace the individual copies of this License 
in the various documents with a single copy that is included in the collection, 
provided that you follow the rules of this License for verbatim copying of each 
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it 
individually under this License, provided you insert a copy of this License 
into the extracted document, and follow this License in all other respects 
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and 
independent documents or works, in or on a volume of a storage or distribution 
medium, is called an "aggregate" if the copyright resulting from the 
compilation is not used to limit the legal rights of the compilation's users 
beyond what the individual works permit. When the Document is included in an 
aggregate, this License does not apply to the other works in the aggregate 
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the 
Document, then if the Document is less than one half of the entire aggregate, 
the Document's Cover Texts may be placed on covers that bracket the Document 
within the aggregate, or the electronic equivalent of covers if the Document is 
in electronic form. Otherwise they must appear on printed covers that bracket 
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute 
translations of the Document under the terms of section 4. Replacing Invariant 
Sections with translations requires special permission from their copyright 
holders, but you may include translations of some or all Invariant Sections in 
addition to the original versions of these Invariant Sections. You may include 
a translation of this License, and all the license notices in the Document, and 
any Warranty Disclaimers, provided that you also include the original English 
version of this License and the original versions of those notices and 
disclaimers. In case of a disagreement between the translation and the original 
version of this License or a notice or disclaimer, the original version will 
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or 
"History", the requirement (section 4) to Preserve its Title (section 1) will 
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as 
expressly provided under this License. Any attempt otherwise to copy, modify, 
sublicense, or distribute it is void, and will automatically terminate your 
rights under this License.

However, if you cease all violation of this License, then your license from a 
particular copyright holder is reinstated (a) provisionally, unless and until 
the copyright holder explicitly and finally terminates your license, and (b) 
permanently, if the copyright holder fails to notify you of the violation by 
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated 
permanently if the copyright holder notifies you of the violation by some 
reasonable means, this is the first time you have received notice of violation 
of this License (for any work) from that copyright holder, and you cure the 
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses 
of parties who have received copies or rights from you under this License. If 
your rights have been terminated and not permanently reinstated, receipt of a 
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free 
Documentation License from time to time. Such new versions will be similar in 
spirit to the present version, but may differ in detail to address new problems 
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the 
Document specifies that a particular numbered version of this License "or any 
later version" applies to it, you have the option of following the terms and 
conditions either of that specified version or of any later version that has 
been published (not as a draft) by the Free Software Foundation. If the 
Document does not specify a version number of this License, you may choose any 
version ever published (not as a draft) by the Free Software Foundation. If the 
Document specifies that a proxy can decide which future versions of this 
License can be used, that proxy's public statement of acceptance of a version 
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide 
Web server that publishes copyrightable works and also provides prominent 
facilities for anybody to edit those works. A public wiki that anybody can edit 
is an example of such a server. A "Massive Multiauthor Collaboration" (or 
"MMC") contained in the site means any set of copyrightable works thus 
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license 
published by Creative Commons Corporation, a not-for-profit corporation with a 
principal place of business in San Francisco, California, as well as future 
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as 
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and 
if all works that were first published under this License somewhere other than 
this MMC, and subsequently incorporated in whole or in part into the MMC, (1) 
had no cover texts or invariant sections, and (2) were thus incorporated prior 
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under 
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC 
is eligible for relicensing.

